project 'SocialBannersApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialBannersApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialBannersApp

  target 'SocialBannersAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocialBannersAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
